print(45*2/10)
num1 = int(input('введите первое число:'))
num2 = int(input('введите второе число:'))
print("Сумма:", num1+num2)
print("Разность:", num1-num2)
print("Произведение:", num1*num2)
num3 = int(input('введите третье число:'))
num4 = int(input('введите четвертое число:'))
print("Площадь:" ,num3*num4)
print("Периметр:", num3+num4)